generate models
lazycoder9/fullstack-learn pull request #4
Opened 2019-06-09 20:21 UTC by lazycoder9

2019-06-13 14:51 UTC, Andrew8xx8 requested changes

2019-06-13 14:51 UTC, Andrew8xx8 commented on test/models/manager_test.rb
> +  # test "the truth" do
Зачем пустые файлы тесты?

2019-06-13 18:34 UTC, lazycoder9 commented on test/models/manager_test.rb
> +  # test "the truth" do
Сгенерились, на все модели. Просто удалить?

2019-07-08 13:19 UTC, Andrew8xx8 commented on test/models/manager_test.rb
> +  # test "the truth" do
Да, надо удалить

2019-07-09 06:24 UTC, lazycoder9 commented on test/models/manager_test.rb
> +  # test "the truth" do
Done

2019-07-09 06:40 UTC, merged